// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AppendLogArgs {
    pub deployment_id: u64,
    pub seq: u32,
    pub stream: String,
    pub text: String,
}

impl From<AppendLogArgs> for super::Reducer {
    fn from(args: AppendLogArgs) -> Self {
        Self::AppendLog {
            deployment_id: args.deployment_id,
            seq: args.seq,
            stream: args.stream,
            text: args.text,
        }
    }
}

impl __sdk::InModule for AppendLogArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `append_log`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait append_log {
    /// Request that the remote module invoke the reducer `append_log` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`append_log:append_log_then`] to run a callback after the reducer completes.
    fn append_log(
        &self,
        deployment_id: u64,
        seq: u32,
        stream: String,
        text: String,
    ) -> __sdk::Result<()> {
        self.append_log_then(deployment_id, seq, stream, text, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `append_log` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn append_log_then(
        &self,
        deployment_id: u64,
        seq: u32,
        stream: String,
        text: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl append_log for super::RemoteReducers {
    fn append_log_then(
        &self,
        deployment_id: u64,
        seq: u32,
        stream: String,
        text: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AppendLogArgs {
                deployment_id,
                seq,
                stream,
                text,
            },
            callback,
        )
    }
}
