// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::application_type::Application;
use super::source_kind_type::SourceKind;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `application`.
///
/// Obtain a handle from the [`ApplicationTableAccess::application`] method on [`super::RemoteTables`],
/// like `ctx.db.application()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.application().on_insert(...)`.
pub struct ApplicationTableHandle<'ctx> {
    imp: __sdk::TableHandle<Application>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `application`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ApplicationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ApplicationTableHandle`], which mediates access to the table `application`.
    fn application(&self) -> ApplicationTableHandle<'_>;
}

impl ApplicationTableAccess for super::RemoteTables {
    fn application(&self) -> ApplicationTableHandle<'_> {
        ApplicationTableHandle {
            imp: self.imp.get_table::<Application>("application"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ApplicationInsertCallbackId(__sdk::CallbackId);
pub struct ApplicationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ApplicationTableHandle<'ctx> {
    type Row = Application;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Application> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ApplicationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ApplicationInsertCallbackId {
        ApplicationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ApplicationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ApplicationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ApplicationDeleteCallbackId {
        ApplicationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ApplicationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ApplicationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ApplicationTableHandle<'ctx> {
    type UpdateCallbackId = ApplicationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ApplicationUpdateCallbackId {
        ApplicationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ApplicationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `application`,
/// which allows point queries on the field of the same name
/// via the [`ApplicationIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.application().id().find(...)`.
pub struct ApplicationIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Application, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ApplicationTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `application`.
    pub fn id(&self) -> ApplicationIdUnique<'ctx> {
        ApplicationIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ApplicationIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Application> {
        self.imp.find(col_val)
    }
}

/// Access to the `name` unique index on the table `application`,
/// which allows point queries on the field of the same name
/// via the [`ApplicationNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.application().name().find(...)`.
pub struct ApplicationNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Application, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ApplicationTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `application`.
    pub fn name(&self) -> ApplicationNameUnique<'ctx> {
        ApplicationNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ApplicationNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Application> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Application>("application");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Application>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Application>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Application`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait applicationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Application`.
    fn application(&self) -> __sdk::__query_builder::Table<Application>;
}

impl applicationQueryTableAccess for __sdk::QueryTableAccessor {
    fn application(&self) -> __sdk::__query_builder::Table<Application> {
        __sdk::__query_builder::Table::new("application")
    }
}
