// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::source_kind_type::SourceKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Application {
    pub id: u64,
    pub name: String,
    pub source_kind: SourceKind,
    pub repo: String,
    pub default_branch: String,
    pub entrypoint: String,
    pub port: u16,
    pub deploy_path: String,
    pub default_strategy: String,
}

impl __sdk::InModule for Application {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Application`.
///
/// Provides typed access to columns for query building.
pub struct ApplicationCols {
    pub id: __sdk::__query_builder::Col<Application, u64>,
    pub name: __sdk::__query_builder::Col<Application, String>,
    pub source_kind: __sdk::__query_builder::Col<Application, SourceKind>,
    pub repo: __sdk::__query_builder::Col<Application, String>,
    pub default_branch: __sdk::__query_builder::Col<Application, String>,
    pub entrypoint: __sdk::__query_builder::Col<Application, String>,
    pub port: __sdk::__query_builder::Col<Application, u16>,
    pub deploy_path: __sdk::__query_builder::Col<Application, String>,
    pub default_strategy: __sdk::__query_builder::Col<Application, String>,
}

impl __sdk::__query_builder::HasCols for Application {
    type Cols = ApplicationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ApplicationCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source_kind: __sdk::__query_builder::Col::new(table_name, "source_kind"),
            repo: __sdk::__query_builder::Col::new(table_name, "repo"),
            default_branch: __sdk::__query_builder::Col::new(table_name, "default_branch"),
            entrypoint: __sdk::__query_builder::Col::new(table_name, "entrypoint"),
            port: __sdk::__query_builder::Col::new(table_name, "port"),
            deploy_path: __sdk::__query_builder::Col::new(table_name, "deploy_path"),
            default_strategy: __sdk::__query_builder::Col::new(table_name, "default_strategy"),
        }
    }
}

/// Indexed column accessor struct for the table `Application`.
///
/// Provides typed access to indexed columns for query building.
pub struct ApplicationIxCols {
    pub id: __sdk::__query_builder::IxCol<Application, u64>,
    pub name: __sdk::__query_builder::IxCol<Application, String>,
}

impl __sdk::__query_builder::HasIxCols for Application {
    type IxCols = ApplicationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ApplicationIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Application {}
