// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::deploy_status_type::DeployStatus;
use super::deployment_type::Deployment;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `deployment`.
///
/// Obtain a handle from the [`DeploymentTableAccess::deployment`] method on [`super::RemoteTables`],
/// like `ctx.db.deployment()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.deployment().on_insert(...)`.
pub struct DeploymentTableHandle<'ctx> {
    imp: __sdk::TableHandle<Deployment>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `deployment`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DeploymentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DeploymentTableHandle`], which mediates access to the table `deployment`.
    fn deployment(&self) -> DeploymentTableHandle<'_>;
}

impl DeploymentTableAccess for super::RemoteTables {
    fn deployment(&self) -> DeploymentTableHandle<'_> {
        DeploymentTableHandle {
            imp: self.imp.get_table::<Deployment>("deployment"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DeploymentInsertCallbackId(__sdk::CallbackId);
pub struct DeploymentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DeploymentTableHandle<'ctx> {
    type Row = Deployment;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Deployment> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DeploymentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DeploymentInsertCallbackId {
        DeploymentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DeploymentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DeploymentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DeploymentDeleteCallbackId {
        DeploymentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DeploymentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DeploymentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DeploymentTableHandle<'ctx> {
    type UpdateCallbackId = DeploymentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DeploymentUpdateCallbackId {
        DeploymentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DeploymentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `deployment`,
/// which allows point queries on the field of the same name
/// via the [`DeploymentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.deployment().id().find(...)`.
pub struct DeploymentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Deployment, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DeploymentTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `deployment`.
    pub fn id(&self) -> DeploymentIdUnique<'ctx> {
        DeploymentIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DeploymentIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Deployment> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Deployment>("deployment");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Deployment>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Deployment>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Deployment`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait deploymentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Deployment`.
    fn deployment(&self) -> __sdk::__query_builder::Table<Deployment>;
}

impl deploymentQueryTableAccess for __sdk::QueryTableAccessor {
    fn deployment(&self) -> __sdk::__query_builder::Table<Deployment> {
        __sdk::__query_builder::Table::new("deployment")
    }
}
