// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::deploy_log_line_type::DeployLogLine;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `deploy_log_line`.
///
/// Obtain a handle from the [`DeployLogLineTableAccess::deploy_log_line`] method on [`super::RemoteTables`],
/// like `ctx.db.deploy_log_line()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.deploy_log_line().on_insert(...)`.
pub struct DeployLogLineTableHandle<'ctx> {
    imp: __sdk::TableHandle<DeployLogLine>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `deploy_log_line`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DeployLogLineTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DeployLogLineTableHandle`], which mediates access to the table `deploy_log_line`.
    fn deploy_log_line(&self) -> DeployLogLineTableHandle<'_>;
}

impl DeployLogLineTableAccess for super::RemoteTables {
    fn deploy_log_line(&self) -> DeployLogLineTableHandle<'_> {
        DeployLogLineTableHandle {
            imp: self.imp.get_table::<DeployLogLine>("deploy_log_line"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DeployLogLineInsertCallbackId(__sdk::CallbackId);
pub struct DeployLogLineDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DeployLogLineTableHandle<'ctx> {
    type Row = DeployLogLine;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DeployLogLine> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DeployLogLineInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DeployLogLineInsertCallbackId {
        DeployLogLineInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DeployLogLineInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DeployLogLineDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DeployLogLineDeleteCallbackId {
        DeployLogLineDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DeployLogLineDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DeployLogLineUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DeployLogLineTableHandle<'ctx> {
    type UpdateCallbackId = DeployLogLineUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DeployLogLineUpdateCallbackId {
        DeployLogLineUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DeployLogLineUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `deploy_log_line`,
/// which allows point queries on the field of the same name
/// via the [`DeployLogLineIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.deploy_log_line().id().find(...)`.
pub struct DeployLogLineIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DeployLogLine, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DeployLogLineTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `deploy_log_line`.
    pub fn id(&self) -> DeployLogLineIdUnique<'ctx> {
        DeployLogLineIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DeployLogLineIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<DeployLogLine> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DeployLogLine>("deploy_log_line");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DeployLogLine>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DeployLogLine>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DeployLogLine`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait deploy_log_lineQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DeployLogLine`.
    fn deploy_log_line(&self) -> __sdk::__query_builder::Table<DeployLogLine>;
}

impl deploy_log_lineQueryTableAccess for __sdk::QueryTableAccessor {
    fn deploy_log_line(&self) -> __sdk::__query_builder::Table<DeployLogLine> {
        __sdk::__query_builder::Table::new("deploy_log_line")
    }
}
