// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DeployLogLine {
    pub id: u64,
    pub deployment_id: u64,
    pub seq: u32,
    pub stream: String,
    pub text: String,
    pub at: __sdk::Timestamp,
}

impl __sdk::InModule for DeployLogLine {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DeployLogLine`.
///
/// Provides typed access to columns for query building.
pub struct DeployLogLineCols {
    pub id: __sdk::__query_builder::Col<DeployLogLine, u64>,
    pub deployment_id: __sdk::__query_builder::Col<DeployLogLine, u64>,
    pub seq: __sdk::__query_builder::Col<DeployLogLine, u32>,
    pub stream: __sdk::__query_builder::Col<DeployLogLine, String>,
    pub text: __sdk::__query_builder::Col<DeployLogLine, String>,
    pub at: __sdk::__query_builder::Col<DeployLogLine, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for DeployLogLine {
    type Cols = DeployLogLineCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DeployLogLineCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            deployment_id: __sdk::__query_builder::Col::new(table_name, "deployment_id"),
            seq: __sdk::__query_builder::Col::new(table_name, "seq"),
            stream: __sdk::__query_builder::Col::new(table_name, "stream"),
            text: __sdk::__query_builder::Col::new(table_name, "text"),
            at: __sdk::__query_builder::Col::new(table_name, "at"),
        }
    }
}

/// Indexed column accessor struct for the table `DeployLogLine`.
///
/// Provides typed access to indexed columns for query building.
pub struct DeployLogLineIxCols {
    pub deployment_id: __sdk::__query_builder::IxCol<DeployLogLine, u64>,
    pub id: __sdk::__query_builder::IxCol<DeployLogLine, u64>,
}

impl __sdk::__query_builder::HasIxCols for DeployLogLine {
    type IxCols = DeployLogLineIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DeployLogLineIxCols {
            deployment_id: __sdk::__query_builder::IxCol::new(table_name, "deployment_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DeployLogLine {}
