// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::workload_report_type::WorkloadReport;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct HeartbeatArgs {
    pub cpu_pct: u8,
    pub mem_pct: u8,
    pub agent_version: String,
    pub workloads: Vec<WorkloadReport>,
}

impl From<HeartbeatArgs> for super::Reducer {
    fn from(args: HeartbeatArgs) -> Self {
        Self::Heartbeat {
            cpu_pct: args.cpu_pct,
            mem_pct: args.mem_pct,
            agent_version: args.agent_version,
            workloads: args.workloads,
        }
    }
}

impl __sdk::InModule for HeartbeatArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `heartbeat`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait heartbeat {
    /// Request that the remote module invoke the reducer `heartbeat` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`heartbeat:heartbeat_then`] to run a callback after the reducer completes.
    fn heartbeat(
        &self,
        cpu_pct: u8,
        mem_pct: u8,
        agent_version: String,
        workloads: Vec<WorkloadReport>,
    ) -> __sdk::Result<()> {
        self.heartbeat_then(cpu_pct, mem_pct, agent_version, workloads, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `heartbeat` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn heartbeat_then(
        &self,
        cpu_pct: u8,
        mem_pct: u8,
        agent_version: String,
        workloads: Vec<WorkloadReport>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl heartbeat for super::RemoteReducers {
    fn heartbeat_then(
        &self,
        cpu_pct: u8,
        mem_pct: u8,
        agent_version: String,
        workloads: Vec<WorkloadReport>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            HeartbeatArgs {
                cpu_pct,
                mem_pct,
                agent_version,
                workloads,
            },
            callback,
        )
    }
}
