// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod agent_binding_type;
pub mod append_log_reducer;
pub mod application_table;
pub mod application_type;
pub mod claim_instance_reducer;
pub mod create_enrollment_token_reducer;
pub mod delete_application_reducer;
pub mod delete_host_reducer;
pub mod deploy_log_line_table;
pub mod deploy_log_line_type;
pub mod deploy_status_type;
pub mod deployment_table;
pub mod deployment_type;
pub mod enroll_host_reducer;
pub mod enrollment_token_type;
pub mod finish_deployment_reducer;
pub mod heartbeat_reducer;
pub mod host_status_type;
pub mod host_table;
pub mod host_type;
pub mod operator_type;
pub mod platform_type;
pub mod queue_deployment_reducer;
pub mod reaper_schedule_type;
pub mod register_application_reducer;
pub mod rollback_deployment_reducer;
pub mod set_host_draining_reducer;
pub mod source_kind_type;
pub mod start_deployment_reducer;
pub mod workload_kind_type;
pub mod workload_report_type;
pub mod workload_table;
pub mod workload_type;

pub use agent_binding_type::AgentBinding;
pub use append_log_reducer::append_log;
pub use application_table::*;
pub use application_type::Application;
pub use claim_instance_reducer::claim_instance;
pub use create_enrollment_token_reducer::create_enrollment_token;
pub use delete_application_reducer::delete_application;
pub use delete_host_reducer::delete_host;
pub use deploy_log_line_table::*;
pub use deploy_log_line_type::DeployLogLine;
pub use deploy_status_type::DeployStatus;
pub use deployment_table::*;
pub use deployment_type::Deployment;
pub use enroll_host_reducer::enroll_host;
pub use enrollment_token_type::EnrollmentToken;
pub use finish_deployment_reducer::finish_deployment;
pub use heartbeat_reducer::heartbeat;
pub use host_status_type::HostStatus;
pub use host_table::*;
pub use host_type::Host;
pub use operator_type::Operator;
pub use platform_type::Platform;
pub use queue_deployment_reducer::queue_deployment;
pub use reaper_schedule_type::ReaperSchedule;
pub use register_application_reducer::register_application;
pub use rollback_deployment_reducer::rollback_deployment;
pub use set_host_draining_reducer::set_host_draining;
pub use source_kind_type::SourceKind;
pub use start_deployment_reducer::start_deployment;
pub use workload_kind_type::WorkloadKind;
pub use workload_report_type::WorkloadReport;
pub use workload_table::*;
pub use workload_type::Workload;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AppendLog {
        deployment_id: u64,
        seq: u32,
        stream: String,
        text: String,
    },
    ClaimInstance,
    CreateEnrollmentToken {
        code: String,
        region: String,
    },
    DeleteApplication {
        app_id: u64,
    },
    DeleteHost {
        host_id: u64,
    },
    EnrollHost {
        code: String,
        name: String,
        address: String,
        platform: Platform,
        os_name: String,
        runtime: String,
        agent_version: String,
    },
    FinishDeployment {
        deployment_id: u64,
        succeeded: bool,
    },
    Heartbeat {
        cpu_pct: u8,
        mem_pct: u8,
        agent_version: String,
        workloads: Vec<WorkloadReport>,
    },
    QueueDeployment {
        app_id: u64,
        host_id: u64,
        commit_sha: String,
        commit_message: String,
        strategy: String,
    },
    RegisterApplication {
        name: String,
        source_kind: SourceKind,
        repo: String,
        default_branch: String,
        entrypoint: String,
        port: u16,
        deploy_path: String,
        default_strategy: String,
    },
    RollbackDeployment {
        deployment_id: u64,
    },
    SetHostDraining {
        host_id: u64,
        draining: bool,
    },
    StartDeployment {
        deployment_id: u64,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AppendLog { .. } => "append_log",
            Reducer::ClaimInstance => "claim_instance",
            Reducer::CreateEnrollmentToken { .. } => "create_enrollment_token",
            Reducer::DeleteApplication { .. } => "delete_application",
            Reducer::DeleteHost { .. } => "delete_host",
            Reducer::EnrollHost { .. } => "enroll_host",
            Reducer::FinishDeployment { .. } => "finish_deployment",
            Reducer::Heartbeat { .. } => "heartbeat",
            Reducer::QueueDeployment { .. } => "queue_deployment",
            Reducer::RegisterApplication { .. } => "register_application",
            Reducer::RollbackDeployment { .. } => "rollback_deployment",
            Reducer::SetHostDraining { .. } => "set_host_draining",
            Reducer::StartDeployment { .. } => "start_deployment",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AppendLog {
                deployment_id,
                seq,
                stream,
                text,
            } => __sats::bsatn::to_vec(&append_log_reducer::AppendLogArgs {
                deployment_id: deployment_id.clone(),
                seq: seq.clone(),
                stream: stream.clone(),
                text: text.clone(),
            }),
            Reducer::ClaimInstance => {
                __sats::bsatn::to_vec(&claim_instance_reducer::ClaimInstanceArgs {})
            }
            Reducer::CreateEnrollmentToken { code, region } => __sats::bsatn::to_vec(
                &create_enrollment_token_reducer::CreateEnrollmentTokenArgs {
                    code: code.clone(),
                    region: region.clone(),
                },
            ),
            Reducer::DeleteApplication { app_id } => {
                __sats::bsatn::to_vec(&delete_application_reducer::DeleteApplicationArgs {
                    app_id: app_id.clone(),
                })
            }
            Reducer::DeleteHost { host_id } => {
                __sats::bsatn::to_vec(&delete_host_reducer::DeleteHostArgs {
                    host_id: host_id.clone(),
                })
            }
            Reducer::EnrollHost {
                code,
                name,
                address,
                platform,
                os_name,
                runtime,
                agent_version,
            } => __sats::bsatn::to_vec(&enroll_host_reducer::EnrollHostArgs {
                code: code.clone(),
                name: name.clone(),
                address: address.clone(),
                platform: platform.clone(),
                os_name: os_name.clone(),
                runtime: runtime.clone(),
                agent_version: agent_version.clone(),
            }),
            Reducer::FinishDeployment {
                deployment_id,
                succeeded,
            } => __sats::bsatn::to_vec(&finish_deployment_reducer::FinishDeploymentArgs {
                deployment_id: deployment_id.clone(),
                succeeded: succeeded.clone(),
            }),
            Reducer::Heartbeat {
                cpu_pct,
                mem_pct,
                agent_version,
                workloads,
            } => __sats::bsatn::to_vec(&heartbeat_reducer::HeartbeatArgs {
                cpu_pct: cpu_pct.clone(),
                mem_pct: mem_pct.clone(),
                agent_version: agent_version.clone(),
                workloads: workloads.clone(),
            }),
            Reducer::QueueDeployment {
                app_id,
                host_id,
                commit_sha,
                commit_message,
                strategy,
            } => __sats::bsatn::to_vec(&queue_deployment_reducer::QueueDeploymentArgs {
                app_id: app_id.clone(),
                host_id: host_id.clone(),
                commit_sha: commit_sha.clone(),
                commit_message: commit_message.clone(),
                strategy: strategy.clone(),
            }),
            Reducer::RegisterApplication {
                name,
                source_kind,
                repo,
                default_branch,
                entrypoint,
                port,
                deploy_path,
                default_strategy,
            } => __sats::bsatn::to_vec(&register_application_reducer::RegisterApplicationArgs {
                name: name.clone(),
                source_kind: source_kind.clone(),
                repo: repo.clone(),
                default_branch: default_branch.clone(),
                entrypoint: entrypoint.clone(),
                port: port.clone(),
                deploy_path: deploy_path.clone(),
                default_strategy: default_strategy.clone(),
            }),
            Reducer::RollbackDeployment { deployment_id } => {
                __sats::bsatn::to_vec(&rollback_deployment_reducer::RollbackDeploymentArgs {
                    deployment_id: deployment_id.clone(),
                })
            }
            Reducer::SetHostDraining { host_id, draining } => {
                __sats::bsatn::to_vec(&set_host_draining_reducer::SetHostDrainingArgs {
                    host_id: host_id.clone(),
                    draining: draining.clone(),
                })
            }
            Reducer::StartDeployment { deployment_id } => {
                __sats::bsatn::to_vec(&start_deployment_reducer::StartDeploymentArgs {
                    deployment_id: deployment_id.clone(),
                })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    application: __sdk::TableUpdate<Application>,
    deploy_log_line: __sdk::TableUpdate<DeployLogLine>,
    deployment: __sdk::TableUpdate<Deployment>,
    host: __sdk::TableUpdate<Host>,
    workload: __sdk::TableUpdate<Workload>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "application" => db_update
                    .application
                    .append(application_table::parse_table_update(table_update)?),
                "deploy_log_line" => db_update
                    .deploy_log_line
                    .append(deploy_log_line_table::parse_table_update(table_update)?),
                "deployment" => db_update
                    .deployment
                    .append(deployment_table::parse_table_update(table_update)?),
                "host" => db_update
                    .host
                    .append(host_table::parse_table_update(table_update)?),
                "workload" => db_update
                    .workload
                    .append(workload_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.application = cache
            .apply_diff_to_table::<Application>("application", &self.application)
            .with_updates_by_pk(|row| &row.id);
        diff.deploy_log_line = cache
            .apply_diff_to_table::<DeployLogLine>("deploy_log_line", &self.deploy_log_line)
            .with_updates_by_pk(|row| &row.id);
        diff.deployment = cache
            .apply_diff_to_table::<Deployment>("deployment", &self.deployment)
            .with_updates_by_pk(|row| &row.id);
        diff.host = cache
            .apply_diff_to_table::<Host>("host", &self.host)
            .with_updates_by_pk(|row| &row.id);
        diff.workload = cache
            .apply_diff_to_table::<Workload>("workload", &self.workload)
            .with_updates_by_pk(|row| &row.id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "application" => db_update
                    .application
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "deploy_log_line" => db_update
                    .deploy_log_line
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "deployment" => db_update
                    .deployment
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "host" => db_update
                    .host
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "workload" => db_update
                    .workload
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "application" => db_update
                    .application
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "deploy_log_line" => db_update
                    .deploy_log_line
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "deployment" => db_update
                    .deployment
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "host" => db_update
                    .host
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "workload" => db_update
                    .workload
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    application: __sdk::TableAppliedDiff<'r, Application>,
    deploy_log_line: __sdk::TableAppliedDiff<'r, DeployLogLine>,
    deployment: __sdk::TableAppliedDiff<'r, Deployment>,
    host: __sdk::TableAppliedDiff<'r, Host>,
    workload: __sdk::TableAppliedDiff<'r, Workload>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Application>(
            "application",
            &self.application,
            event,
        );
        callbacks.invoke_table_row_callbacks::<DeployLogLine>(
            "deploy_log_line",
            &self.deploy_log_line,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Deployment>("deployment", &self.deployment, event);
        callbacks.invoke_table_row_callbacks::<Host>("host", &self.host, event);
        callbacks.invoke_table_row_callbacks::<Workload>("workload", &self.workload, event);
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        application_table::register_table(client_cache);
        deploy_log_line_table::register_table(client_cache);
        deployment_table::register_table(client_cache);
        host_table::register_table(client_cache);
        workload_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "application",
        "deploy_log_line",
        "deployment",
        "host",
        "workload",
    ];
}
