// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Operator {
    pub identity: __sdk::Identity,
    pub claimed_at: __sdk::Timestamp,
}

impl __sdk::InModule for Operator {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Operator`.
///
/// Provides typed access to columns for query building.
pub struct OperatorCols {
    pub identity: __sdk::__query_builder::Col<Operator, __sdk::Identity>,
    pub claimed_at: __sdk::__query_builder::Col<Operator, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Operator {
    type Cols = OperatorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OperatorCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            claimed_at: __sdk::__query_builder::Col::new(table_name, "claimed_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Operator`.
///
/// Provides typed access to indexed columns for query building.
pub struct OperatorIxCols {
    pub identity: __sdk::__query_builder::IxCol<Operator, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Operator {
    type IxCols = OperatorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OperatorIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Operator {}
