// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct QueueDeploymentArgs {
    pub app_id: u64,
    pub host_id: u64,
    pub commit_sha: String,
    pub commit_message: String,
    pub strategy: String,
}

impl From<QueueDeploymentArgs> for super::Reducer {
    fn from(args: QueueDeploymentArgs) -> Self {
        Self::QueueDeployment {
            app_id: args.app_id,
            host_id: args.host_id,
            commit_sha: args.commit_sha,
            commit_message: args.commit_message,
            strategy: args.strategy,
        }
    }
}

impl __sdk::InModule for QueueDeploymentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `queue_deployment`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait queue_deployment {
    /// Request that the remote module invoke the reducer `queue_deployment` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`queue_deployment:queue_deployment_then`] to run a callback after the reducer completes.
    fn queue_deployment(
        &self,
        app_id: u64,
        host_id: u64,
        commit_sha: String,
        commit_message: String,
        strategy: String,
    ) -> __sdk::Result<()> {
        self.queue_deployment_then(
            app_id,
            host_id,
            commit_sha,
            commit_message,
            strategy,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `queue_deployment` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn queue_deployment_then(
        &self,
        app_id: u64,
        host_id: u64,
        commit_sha: String,
        commit_message: String,
        strategy: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl queue_deployment for super::RemoteReducers {
    fn queue_deployment_then(
        &self,
        app_id: u64,
        host_id: u64,
        commit_sha: String,
        commit_message: String,
        strategy: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            QueueDeploymentArgs {
                app_id,
                host_id,
                commit_sha,
                commit_message,
                strategy,
            },
            callback,
        )
    }
}
