// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::source_kind_type::SourceKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterApplicationArgs {
    pub name: String,
    pub source_kind: SourceKind,
    pub repo: String,
    pub default_branch: String,
    pub entrypoint: String,
    pub port: u16,
    pub deploy_path: String,
    pub default_strategy: String,
}

impl From<RegisterApplicationArgs> for super::Reducer {
    fn from(args: RegisterApplicationArgs) -> Self {
        Self::RegisterApplication {
            name: args.name,
            source_kind: args.source_kind,
            repo: args.repo,
            default_branch: args.default_branch,
            entrypoint: args.entrypoint,
            port: args.port,
            deploy_path: args.deploy_path,
            default_strategy: args.default_strategy,
        }
    }
}

impl __sdk::InModule for RegisterApplicationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_application`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_application {
    /// Request that the remote module invoke the reducer `register_application` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_application:register_application_then`] to run a callback after the reducer completes.
    fn register_application(
        &self,
        name: String,
        source_kind: SourceKind,
        repo: String,
        default_branch: String,
        entrypoint: String,
        port: u16,
        deploy_path: String,
        default_strategy: String,
    ) -> __sdk::Result<()> {
        self.register_application_then(
            name,
            source_kind,
            repo,
            default_branch,
            entrypoint,
            port,
            deploy_path,
            default_strategy,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `register_application` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_application_then(
        &self,
        name: String,
        source_kind: SourceKind,
        repo: String,
        default_branch: String,
        entrypoint: String,
        port: u16,
        deploy_path: String,
        default_strategy: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_application for super::RemoteReducers {
    fn register_application_then(
        &self,
        name: String,
        source_kind: SourceKind,
        repo: String,
        default_branch: String,
        entrypoint: String,
        port: u16,
        deploy_path: String,
        default_strategy: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterApplicationArgs {
                name,
                source_kind,
                repo,
                default_branch,
                entrypoint,
                port,
                deploy_path,
                default_strategy,
            },
            callback,
        )
    }
}
