// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RollbackDeploymentArgs {
    pub deployment_id: u64,
}

impl From<RollbackDeploymentArgs> for super::Reducer {
    fn from(args: RollbackDeploymentArgs) -> Self {
        Self::RollbackDeployment {
            deployment_id: args.deployment_id,
        }
    }
}

impl __sdk::InModule for RollbackDeploymentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `rollback_deployment`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait rollback_deployment {
    /// Request that the remote module invoke the reducer `rollback_deployment` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`rollback_deployment:rollback_deployment_then`] to run a callback after the reducer completes.
    fn rollback_deployment(&self, deployment_id: u64) -> __sdk::Result<()> {
        self.rollback_deployment_then(deployment_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `rollback_deployment` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn rollback_deployment_then(
        &self,
        deployment_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl rollback_deployment for super::RemoteReducers {
    fn rollback_deployment_then(
        &self,
        deployment_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RollbackDeploymentArgs { deployment_id }, callback)
    }
}
