// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetHostDrainingArgs {
    pub host_id: u64,
    pub draining: bool,
}

impl From<SetHostDrainingArgs> for super::Reducer {
    fn from(args: SetHostDrainingArgs) -> Self {
        Self::SetHostDraining {
            host_id: args.host_id,
            draining: args.draining,
        }
    }
}

impl __sdk::InModule for SetHostDrainingArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_host_draining`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_host_draining {
    /// Request that the remote module invoke the reducer `set_host_draining` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_host_draining:set_host_draining_then`] to run a callback after the reducer completes.
    fn set_host_draining(&self, host_id: u64, draining: bool) -> __sdk::Result<()> {
        self.set_host_draining_then(host_id, draining, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_host_draining` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_host_draining_then(
        &self,
        host_id: u64,
        draining: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_host_draining for super::RemoteReducers {
    fn set_host_draining_then(
        &self,
        host_id: u64,
        draining: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetHostDrainingArgs { host_id, draining }, callback)
    }
}
