// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AgentBinding {
    pub identity: __sdk::Identity,
    pub host_id: u64,
    pub bound_at: __sdk::Timestamp,
}

impl __sdk::InModule for AgentBinding {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AgentBinding`.
///
/// Provides typed access to columns for query building.
pub struct AgentBindingCols {
    pub identity: __sdk::__query_builder::Col<AgentBinding, __sdk::Identity>,
    pub host_id: __sdk::__query_builder::Col<AgentBinding, u64>,
    pub bound_at: __sdk::__query_builder::Col<AgentBinding, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for AgentBinding {
    type Cols = AgentBindingCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgentBindingCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            host_id: __sdk::__query_builder::Col::new(table_name, "host_id"),
            bound_at: __sdk::__query_builder::Col::new(table_name, "bound_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AgentBinding`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgentBindingIxCols {
    pub host_id: __sdk::__query_builder::IxCol<AgentBinding, u64>,
    pub identity: __sdk::__query_builder::IxCol<AgentBinding, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for AgentBinding {
    type IxCols = AgentBindingIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgentBindingIxCols {
            host_id: __sdk::__query_builder::IxCol::new(table_name, "host_id"),
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AgentBinding {}
