// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteHostArgs {
    pub host_id: u64,
}

impl From<DeleteHostArgs> for super::Reducer {
    fn from(args: DeleteHostArgs) -> Self {
        Self::DeleteHost {
            host_id: args.host_id,
        }
    }
}

impl __sdk::InModule for DeleteHostArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_host`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_host {
    /// Request that the remote module invoke the reducer `delete_host` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`delete_host:delete_host_then`] to run a callback after the reducer completes.
    fn delete_host(&self, host_id: u64) -> __sdk::Result<()> {
        self.delete_host_then(host_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `delete_host` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn delete_host_then(
        &self,
        host_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl delete_host for super::RemoteReducers {
    fn delete_host_then(
        &self,
        host_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DeleteHostArgs { host_id }, callback)
    }
}
