// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::deploy_status_type::DeployStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Deployment {
    pub id: u64,
    pub app_id: u64,
    pub host_id: u64,
    pub commit_sha: String,
    pub commit_message: String,
    pub strategy: String,
    pub status: DeployStatus,
    pub queued_at: __sdk::Timestamp,
    pub started_at: Option<__sdk::Timestamp>,
    pub finished_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for Deployment {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Deployment`.
///
/// Provides typed access to columns for query building.
pub struct DeploymentCols {
    pub id: __sdk::__query_builder::Col<Deployment, u64>,
    pub app_id: __sdk::__query_builder::Col<Deployment, u64>,
    pub host_id: __sdk::__query_builder::Col<Deployment, u64>,
    pub commit_sha: __sdk::__query_builder::Col<Deployment, String>,
    pub commit_message: __sdk::__query_builder::Col<Deployment, String>,
    pub strategy: __sdk::__query_builder::Col<Deployment, String>,
    pub status: __sdk::__query_builder::Col<Deployment, DeployStatus>,
    pub queued_at: __sdk::__query_builder::Col<Deployment, __sdk::Timestamp>,
    pub started_at: __sdk::__query_builder::Col<Deployment, Option<__sdk::Timestamp>>,
    pub finished_at: __sdk::__query_builder::Col<Deployment, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for Deployment {
    type Cols = DeploymentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DeploymentCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            app_id: __sdk::__query_builder::Col::new(table_name, "app_id"),
            host_id: __sdk::__query_builder::Col::new(table_name, "host_id"),
            commit_sha: __sdk::__query_builder::Col::new(table_name, "commit_sha"),
            commit_message: __sdk::__query_builder::Col::new(table_name, "commit_message"),
            strategy: __sdk::__query_builder::Col::new(table_name, "strategy"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            queued_at: __sdk::__query_builder::Col::new(table_name, "queued_at"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
            finished_at: __sdk::__query_builder::Col::new(table_name, "finished_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Deployment`.
///
/// Provides typed access to indexed columns for query building.
pub struct DeploymentIxCols {
    pub app_id: __sdk::__query_builder::IxCol<Deployment, u64>,
    pub host_id: __sdk::__query_builder::IxCol<Deployment, u64>,
    pub id: __sdk::__query_builder::IxCol<Deployment, u64>,
}

impl __sdk::__query_builder::HasIxCols for Deployment {
    type IxCols = DeploymentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DeploymentIxCols {
            app_id: __sdk::__query_builder::IxCol::new(table_name, "app_id"),
            host_id: __sdk::__query_builder::IxCol::new(table_name, "host_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Deployment {}
