// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::platform_type::Platform;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EnrollHostArgs {
    pub code: String,
    pub name: String,
    pub address: String,
    pub platform: Platform,
    pub os_name: String,
    pub runtime: String,
    pub agent_version: String,
}

impl From<EnrollHostArgs> for super::Reducer {
    fn from(args: EnrollHostArgs) -> Self {
        Self::EnrollHost {
            code: args.code,
            name: args.name,
            address: args.address,
            platform: args.platform,
            os_name: args.os_name,
            runtime: args.runtime,
            agent_version: args.agent_version,
        }
    }
}

impl __sdk::InModule for EnrollHostArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `enroll_host`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait enroll_host {
    /// Request that the remote module invoke the reducer `enroll_host` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`enroll_host:enroll_host_then`] to run a callback after the reducer completes.
    fn enroll_host(
        &self,
        code: String,
        name: String,
        address: String,
        platform: Platform,
        os_name: String,
        runtime: String,
        agent_version: String,
    ) -> __sdk::Result<()> {
        self.enroll_host_then(
            code,
            name,
            address,
            platform,
            os_name,
            runtime,
            agent_version,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `enroll_host` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn enroll_host_then(
        &self,
        code: String,
        name: String,
        address: String,
        platform: Platform,
        os_name: String,
        runtime: String,
        agent_version: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl enroll_host for super::RemoteReducers {
    fn enroll_host_then(
        &self,
        code: String,
        name: String,
        address: String,
        platform: Platform,
        os_name: String,
        runtime: String,
        agent_version: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            EnrollHostArgs {
                code,
                name,
                address,
                platform,
                os_name,
                runtime,
                agent_version,
            },
            callback,
        )
    }
}
