// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EnrollmentToken {
    pub code: String,
    pub region: String,
    pub created_at: __sdk::Timestamp,
    pub consumed_by: Option<u64>,
}

impl __sdk::InModule for EnrollmentToken {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EnrollmentToken`.
///
/// Provides typed access to columns for query building.
pub struct EnrollmentTokenCols {
    pub code: __sdk::__query_builder::Col<EnrollmentToken, String>,
    pub region: __sdk::__query_builder::Col<EnrollmentToken, String>,
    pub created_at: __sdk::__query_builder::Col<EnrollmentToken, __sdk::Timestamp>,
    pub consumed_by: __sdk::__query_builder::Col<EnrollmentToken, Option<u64>>,
}

impl __sdk::__query_builder::HasCols for EnrollmentToken {
    type Cols = EnrollmentTokenCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EnrollmentTokenCols {
            code: __sdk::__query_builder::Col::new(table_name, "code"),
            region: __sdk::__query_builder::Col::new(table_name, "region"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            consumed_by: __sdk::__query_builder::Col::new(table_name, "consumed_by"),
        }
    }
}

/// Indexed column accessor struct for the table `EnrollmentToken`.
///
/// Provides typed access to indexed columns for query building.
pub struct EnrollmentTokenIxCols {
    pub code: __sdk::__query_builder::IxCol<EnrollmentToken, String>,
}

impl __sdk::__query_builder::HasIxCols for EnrollmentToken {
    type IxCols = EnrollmentTokenIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EnrollmentTokenIxCols {
            code: __sdk::__query_builder::IxCol::new(table_name, "code"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EnrollmentToken {}
