// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FinishDeploymentArgs {
    pub deployment_id: u64,
    pub succeeded: bool,
}

impl From<FinishDeploymentArgs> for super::Reducer {
    fn from(args: FinishDeploymentArgs) -> Self {
        Self::FinishDeployment {
            deployment_id: args.deployment_id,
            succeeded: args.succeeded,
        }
    }
}

impl __sdk::InModule for FinishDeploymentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `finish_deployment`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait finish_deployment {
    /// Request that the remote module invoke the reducer `finish_deployment` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`finish_deployment:finish_deployment_then`] to run a callback after the reducer completes.
    fn finish_deployment(&self, deployment_id: u64, succeeded: bool) -> __sdk::Result<()> {
        self.finish_deployment_then(deployment_id, succeeded, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `finish_deployment` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn finish_deployment_then(
        &self,
        deployment_id: u64,
        succeeded: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl finish_deployment for super::RemoteReducers {
    fn finish_deployment_then(
        &self,
        deployment_id: u64,
        succeeded: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            FinishDeploymentArgs {
                deployment_id,
                succeeded,
            },
            callback,
        )
    }
}
