// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::host_status_type::HostStatus;
use super::host_type::Host;
use super::platform_type::Platform;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `host`.
///
/// Obtain a handle from the [`HostTableAccess::host`] method on [`super::RemoteTables`],
/// like `ctx.db.host()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.host().on_insert(...)`.
pub struct HostTableHandle<'ctx> {
    imp: __sdk::TableHandle<Host>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `host`.
///
/// Implemented for [`super::RemoteTables`].
pub trait HostTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`HostTableHandle`], which mediates access to the table `host`.
    fn host(&self) -> HostTableHandle<'_>;
}

impl HostTableAccess for super::RemoteTables {
    fn host(&self) -> HostTableHandle<'_> {
        HostTableHandle {
            imp: self.imp.get_table::<Host>("host"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct HostInsertCallbackId(__sdk::CallbackId);
pub struct HostDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for HostTableHandle<'ctx> {
    type Row = Host;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Host> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = HostInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HostInsertCallbackId {
        HostInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HostInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = HostDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HostDeleteCallbackId {
        HostDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HostDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct HostUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for HostTableHandle<'ctx> {
    type UpdateCallbackId = HostUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HostUpdateCallbackId {
        HostUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HostUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `host`,
/// which allows point queries on the field of the same name
/// via the [`HostIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.host().id().find(...)`.
pub struct HostIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Host, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> HostTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `host`.
    pub fn id(&self) -> HostIdUnique<'ctx> {
        HostIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> HostIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Host> {
        self.imp.find(col_val)
    }
}

/// Access to the `name` unique index on the table `host`,
/// which allows point queries on the field of the same name
/// via the [`HostNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.host().name().find(...)`.
pub struct HostNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Host, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> HostTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `host`.
    pub fn name(&self) -> HostNameUnique<'ctx> {
        HostNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> HostNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Host> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Host>("host");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Host>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Host>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Host`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait hostQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Host`.
    fn host(&self) -> __sdk::__query_builder::Table<Host>;
}

impl hostQueryTableAccess for __sdk::QueryTableAccessor {
    fn host(&self) -> __sdk::__query_builder::Table<Host> {
        __sdk::__query_builder::Table::new("host")
    }
}
