// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::host_status_type::HostStatus;
use super::platform_type::Platform;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Host {
    pub id: u64,
    pub name: String,
    pub region: String,
    pub address: String,
    pub platform: Platform,
    pub os_name: String,
    pub runtime: String,
    pub agent_version: String,
    pub status: HostStatus,
    pub cpu_pct: u8,
    pub mem_pct: u8,
    pub workload_count: u32,
    pub last_seen: __sdk::Timestamp,
    pub enrolled_at: __sdk::Timestamp,
}

impl __sdk::InModule for Host {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Host`.
///
/// Provides typed access to columns for query building.
pub struct HostCols {
    pub id: __sdk::__query_builder::Col<Host, u64>,
    pub name: __sdk::__query_builder::Col<Host, String>,
    pub region: __sdk::__query_builder::Col<Host, String>,
    pub address: __sdk::__query_builder::Col<Host, String>,
    pub platform: __sdk::__query_builder::Col<Host, Platform>,
    pub os_name: __sdk::__query_builder::Col<Host, String>,
    pub runtime: __sdk::__query_builder::Col<Host, String>,
    pub agent_version: __sdk::__query_builder::Col<Host, String>,
    pub status: __sdk::__query_builder::Col<Host, HostStatus>,
    pub cpu_pct: __sdk::__query_builder::Col<Host, u8>,
    pub mem_pct: __sdk::__query_builder::Col<Host, u8>,
    pub workload_count: __sdk::__query_builder::Col<Host, u32>,
    pub last_seen: __sdk::__query_builder::Col<Host, __sdk::Timestamp>,
    pub enrolled_at: __sdk::__query_builder::Col<Host, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Host {
    type Cols = HostCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HostCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            region: __sdk::__query_builder::Col::new(table_name, "region"),
            address: __sdk::__query_builder::Col::new(table_name, "address"),
            platform: __sdk::__query_builder::Col::new(table_name, "platform"),
            os_name: __sdk::__query_builder::Col::new(table_name, "os_name"),
            runtime: __sdk::__query_builder::Col::new(table_name, "runtime"),
            agent_version: __sdk::__query_builder::Col::new(table_name, "agent_version"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            cpu_pct: __sdk::__query_builder::Col::new(table_name, "cpu_pct"),
            mem_pct: __sdk::__query_builder::Col::new(table_name, "mem_pct"),
            workload_count: __sdk::__query_builder::Col::new(table_name, "workload_count"),
            last_seen: __sdk::__query_builder::Col::new(table_name, "last_seen"),
            enrolled_at: __sdk::__query_builder::Col::new(table_name, "enrolled_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Host`.
///
/// Provides typed access to indexed columns for query building.
pub struct HostIxCols {
    pub id: __sdk::__query_builder::IxCol<Host, u64>,
    pub name: __sdk::__query_builder::IxCol<Host, String>,
}

impl __sdk::__query_builder::HasIxCols for Host {
    type IxCols = HostIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HostIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Host {}
