// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::workload_kind_type::WorkloadKind;
use super::workload_type::Workload;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `workload`.
///
/// Obtain a handle from the [`WorkloadTableAccess::workload`] method on [`super::RemoteTables`],
/// like `ctx.db.workload()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.workload().on_insert(...)`.
pub struct WorkloadTableHandle<'ctx> {
    imp: __sdk::TableHandle<Workload>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `workload`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorkloadTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorkloadTableHandle`], which mediates access to the table `workload`.
    fn workload(&self) -> WorkloadTableHandle<'_>;
}

impl WorkloadTableAccess for super::RemoteTables {
    fn workload(&self) -> WorkloadTableHandle<'_> {
        WorkloadTableHandle {
            imp: self.imp.get_table::<Workload>("workload"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorkloadInsertCallbackId(__sdk::CallbackId);
pub struct WorkloadDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorkloadTableHandle<'ctx> {
    type Row = Workload;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Workload> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorkloadInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorkloadInsertCallbackId {
        WorkloadInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorkloadInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorkloadDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorkloadDeleteCallbackId {
        WorkloadDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorkloadDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorkloadUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorkloadTableHandle<'ctx> {
    type UpdateCallbackId = WorkloadUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorkloadUpdateCallbackId {
        WorkloadUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorkloadUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `workload`,
/// which allows point queries on the field of the same name
/// via the [`WorkloadIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.workload().id().find(...)`.
pub struct WorkloadIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Workload, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorkloadTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `workload`.
    pub fn id(&self) -> WorkloadIdUnique<'ctx> {
        WorkloadIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorkloadIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Workload> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Workload>("workload");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Workload>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Workload>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Workload`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait workloadQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Workload`.
    fn workload(&self) -> __sdk::__query_builder::Table<Workload>;
}

impl workloadQueryTableAccess for __sdk::QueryTableAccessor {
    fn workload(&self) -> __sdk::__query_builder::Table<Workload> {
        __sdk::__query_builder::Table::new("workload")
    }
}
