// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::workload_kind_type::WorkloadKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Workload {
    pub id: u64,
    pub host_id: u64,
    pub name: String,
    pub kind: WorkloadKind,
    pub state: String,
}

impl __sdk::InModule for Workload {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Workload`.
///
/// Provides typed access to columns for query building.
pub struct WorkloadCols {
    pub id: __sdk::__query_builder::Col<Workload, u64>,
    pub host_id: __sdk::__query_builder::Col<Workload, u64>,
    pub name: __sdk::__query_builder::Col<Workload, String>,
    pub kind: __sdk::__query_builder::Col<Workload, WorkloadKind>,
    pub state: __sdk::__query_builder::Col<Workload, String>,
}

impl __sdk::__query_builder::HasCols for Workload {
    type Cols = WorkloadCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorkloadCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            host_id: __sdk::__query_builder::Col::new(table_name, "host_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
        }
    }
}

/// Indexed column accessor struct for the table `Workload`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorkloadIxCols {
    pub host_id: __sdk::__query_builder::IxCol<Workload, u64>,
    pub id: __sdk::__query_builder::IxCol<Workload, u64>,
}

impl __sdk::__query_builder::HasIxCols for Workload {
    type IxCols = WorkloadIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorkloadIxCols {
            host_id: __sdk::__query_builder::IxCol::new(table_name, "host_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Workload {}
